apiVersion: v1
kind: Service
metadata:
  name: visualising-stocks-service
spec:
  selector:
    app: visualising-stocks
  ports:
  - protocol: TCP
    port: 80              # Hizmetin dışarıdan erişileceği port
    targetPort: 3000      # Pod içindeki uygulamanın portu
    nodePort: 31080       # VPS dışından erişmek için bu port (30000–32767 arası bir sayı olmalı)
  type: NodePort
